name: Release
on:
  release:
    types: [released]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        # platform: [ubuntu-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            executable: chronus_sync.${{ github.event.release.tag_name }}
            target: Linux
          - platform: windows-latest
            executable: chronus_sync.${{ github.event.release.tag_name }}.exe
            target: Windows

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Download Go dependencies packages
        run: go get -t ./src

      - name: Build tool
        run: go build -o ${{ matrix.executable }} -v ./src

      - name: Publish to S3 bucket
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ${{ matrix.executable }}'
          destination_dir: 'build'