name: Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-18.04, windows-2019]
        include:
          - platform: ubuntu-18.04
            executable: chronus_sync
            target: Linux
          - platform: windows-2019
            executable: chronus_sync.exe
            target: Windows

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Download Go dependencies packages
        run: go get -t ./src

      - name: Build tool
        run: go build -o ${{ matrix.executable }} -v ./src

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload file to S3
        run: |
          aws s3 cp ./${{ matrix.executable }} s3://${{ secrets.AWS_BUCKET }}/${{ matrix.executable }} --quiet

  push:
    needs: build
    runs-on: ubuntu-18.04
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Download files from S3
        env:
          BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          aws s3 sync --include="chronus_*" s3://$BUCKET ./ --quiet

      - name: Edit the release to attach built files
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'chronus_*'
